name: release

on:
  workflow_run:
    workflows: [test]
    branches: [main]
    types: [completed]
  workflow_dispatch:


jobs:
  release:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    outputs:
      published: ${{ steps.release.outputs.published }}
      release-version: ${{ steps.release.outputs.release-version }}
      release-version-major: ${{ steps.release.outputs.release-version-major }}
      release-version-minor: ${{ steps.release.outputs.release-version-minor }}

    steps:
      - uses: actions/checkout@v3
      - id: release
        uses: ahmadnassri/action-semantic-release@v2
        with:
          config: ${{ github.workspace }}/.semantic.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  alias:
    needs: release

    if: needs.release.outputs.published == 'true'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        alias:
          - version: v${{ needs.release.outputs.release-version-major }}
          - version: v${{ needs.release.outputs.release-version-major }}.${{ needs.release.outputs.release-version-minor }}

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const tag = 'tags/${{ matrix.alias.version }}'
            const repo = {
              owner: context.repo.owner,
              repo: context.repo.repo
            }

            await github.rest.git.deleteRef({ ...repo, ref: tag }).catch(() => {})
            await github.rest.git.createRef({ ...repo, ref: `refs/${tag}` , sha: process.env.GITHUB_SHA })

  publish:
    needs: release

    if: needs.release.outputs.published == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: buildx-

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      # login to docker hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # login to github container registry
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # publish
      - uses: docker/build-push-action@v4
        with:
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            u4ic/${{ github.event.repository.name }}:latest
            u4ic/${{ github.event.repository.name }}:v${{ needs.release.outputs.release-version-major }}
            u4ic/${{ github.event.repository.name }}:v${{ needs.release.outputs.release-version }}
            ghcr.io/euphoricsystems/${{ github.event.repository.name }}:latest
            ghcr.io/euphoricsystems/${{ github.event.repository.name }}:v${{ needs.release.outputs.release-version-major }}
            ghcr.io/euphoricsystems/${{ github.event.repository.name }}:v${{ needs.release.outputs.release-version }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.version=${{ needs.release.outputs.release-version }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
