name: test

on: [push, pull_request]

defaults:
  run:
    working-directory: action

jobs:
  deduplicate:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    # run on external PRs, but on internal PRs as they'll be run by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - run: echo ::warning ::skipped duplicate run
        working-directory: .

  audit:
    timeout-minutes: 5

    needs: deduplicate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - run: yarn audit --audit-level=critical

  test:
    timeout-minutes: 5

    needs: audit

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ hashFiles('**/yarn.lock') }}

      - run: yarn
      - run: yarn test:ci
